yes

diff --git a/.github/workflows/test2.yml b/.github/workflows/test2.yml
--- a/.github/workflows/test2.yml
+++ b/.github/workflows/test2.yml
@@ -40,7 +40,7 @@ jobs:
         id: run_tests_3
         run: |
           echo "Running tests..."
-          exit 1  # Simulate failure
+          exit 3  # Simulate failure
         continue-on-error: true
 
       - name: Log Test Failure
